const root = ReactDOM.createRoot(document.getElementById("root"));

const ChildComponent = ({ user }) => {
    return (
        <div id="user-container">
            {user.map((u) => <div>
                <h1>{u.first_name}</h1>
                <h2>{u.email}</h2>
                <h3>{u.gender}</h3>
                {u.isStudent ? <p> Student</p> : <p>Not Student</p>}
            </div>)}
        </div>
    )
}
const ParentComponent = () => {
    let user = [{
        "id": 1,
        "first_name": "Sharline",
        "last_name": "Blundon",
        "email": "sblundon0@nifty.com",
        "gender": "Non-binary",
        "isStudent": false
    }, {
        "id": 2,
        "first_name": "Harmonia",
        "last_name": "Balden",
        "email": "hbalden1@bigcartel.com",
        "gender": "Female",
        "isStudent": false
    }, {
        "id": 3,
        "first_name": "Dorie",
        "last_name": "Behneke",
        "email": "dbehneke2@newyorker.com",
        "gender": "Female",
        "isStudent": false
    }, {
        "id": 4,
        "first_name": "Paolina",
        "last_name": "Goldin",
        "email": "pgoldin3@liveinternet.ru",
        "gender": "Female",
        "isStudent": false
    }, {
        "id": 5,
        "first_name": "Agnese",
        "last_name": "Storkes",
        "email": "astorkes4@prlog.org",
        "gender": "Genderfluid",
        "isStudent": true
    }, {
        "id": 6,
        "first_name": "Monte",
        "last_name": "Westgarth",
        "email": "mwestgarth5@illinois.edu",
        "gender": "Male",
        "isStudent": true
    }, {
        "id": 7,
        "first_name": "Lanni",
        "last_name": "Cornelissen",
        "email": "lcornelissen6@behance.net",
        "gender": "Female",
        "isStudent": false
    }, {
        "id": 8,
        "first_name": "Gian",
        "last_name": "Diament",
        "email": "gdiament7@technorati.com",
        "gender": "Male",
        "isStudent": false
    }, {
        "id": 9,
        "first_name": "Poul",
        "last_name": "Boulton",
        "email": "pboulton8@upenn.edu",
        "gender": "Male",
        "isStudent": false
    }, {
        "id": 10,
        "first_name": "Gerek",
        "last_name": "Cawdron",
        "email": "gcawdron9@dropbox.com",
        "gender": "Male",
        "isStudent": true
    }, {
        "id": 11,
        "first_name": "Georas",
        "last_name": "Lorenzini",
        "email": "glorenzinia@gov.uk",
        "gender": "Male",
        "isStudent": false
    }, {
        "id": 12,
        "first_name": "Aubrette",
        "last_name": "Secret",
        "email": "asecretb@bbb.org",
        "gender": "Female",
        "isStudent": false
    }, {
        "id": 13,
        "first_name": "Miller",
        "last_name": "Slipper",
        "email": "mslipperc@spotify.com",
        "gender": "Non-binary",
        "isStudent": false
    }, {
        "id": 14,
        "first_name": "Violante",
        "last_name": "Pennetta",
        "email": "vpennettad@npr.org",
        "gender": "Female",
        "isStudent": false
    }, {
        "id": 15,
        "first_name": "Phil",
        "last_name": "Eddleston",
        "email": "peddlestone@hibu.com",
        "gender": "Male",
        "isStudent": true
    }, {
        "id": 16,
        "first_name": "Ferdinande",
        "last_name": "Brightman",
        "email": "fbrightmanf@sfgate.com",
        "gender": "Female",
        "isStudent": true
    }, {
        "id": 17,
        "first_name": "Letty",
        "last_name": "Dumbare",
        "email": "ldumbareg@homestead.com",
        "gender": "Female",
        "isStudent": false
    }, {
        "id": 18,
        "first_name": "Garrick",
        "last_name": "Colleton",
        "email": "gcolletonh@istockphoto.com",
        "gender": "Male",
        "isStudent": false
    }, {
        "id": 19,
        "first_name": "Kermy",
        "last_name": "Burk",
        "email": "kburki@admin.ch",
        "gender": "Genderfluid",
        "isStudent": false
    }, {
        "id": 20,
        "first_name": "Harley",
        "last_name": "Jeckells",
        "email": "hjeckellsj@businessweek.com",
        "gender": "Female",
        "isStudent": false
    }, {
        "id": 21,
        "first_name": "Ty",
        "last_name": "Rickwood",
        "email": "trickwoodk@ca.gov",
        "gender": "Male",
        "isStudent": false
    }, {
        "id": 22,
        "first_name": "Gran",
        "last_name": "Mace",
        "email": "gmacel@sciencedaily.com",
        "gender": "Male",
        "isStudent": false
    }, {
        "id": 23,
        "first_name": "Weylin",
        "last_name": "Schimonek",
        "email": "wschimonekm@addtoany.com",
        "gender": "Male",
        "isStudent": false
    }, {
        "id": 24,
        "first_name": "Viv",
        "last_name": "Bentson",
        "email": "vbentsonn@drupal.org",
        "gender": "Female",
        "isStudent": true
    }, {
        "id": 25,
        "first_name": "Roi",
        "last_name": "Deeny",
        "email": "rdeenyo@examiner.com",
        "gender": "Male",
        "isStudent": false
    }, {
        "id": 26,
        "first_name": "Bill",
        "last_name": "Bilsford",
        "email": "bbilsfordp@cmu.edu",
        "gender": "Female",
        "isStudent": true
    }, {
        "id": 27,
        "first_name": "Norah",
        "last_name": "Perschke",
        "email": "nperschkeq@bbb.org",
        "gender": "Female",
        "isStudent": true
    }, {
        "id": 28,
        "first_name": "Ethe",
        "last_name": "Wadwell",
        "email": "ewadwellr@tinyurl.com",
        "gender": "Genderfluid",
        "isStudent": false
    }, {
        "id": 29,
        "first_name": "Noll",
        "last_name": "Farmer",
        "email": "nfarmers@people.com.cn",
        "gender": "Male",
        "isStudent": false
    }, {
        "id": 30,
        "first_name": "Siouxie",
        "last_name": "Domonkos",
        "email": "sdomonkost@ning.com",
        "gender": "Female",
        "isStudent": false
    }]
    return (<div>
        {/* <ChildComponent {...user[0]} isStudent={false} />
        <ChildComponent {...user[1]} isStudent={true} /> */}
        <ChildComponent user={user} />
    </div>)
}
root.render(<ParentComponent />)